// Mocks generated by Mockito 5.4.6 from annotations
// in inventory_app/test/viewmodels_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:inventory_app/domain/models/product.dart' as _i4;
import 'package:inventory_app/domain/models/product_filter.dart' as _i5;
import 'package:inventory_app/domain/models/stock_adjustment_reason.dart'
    as _i6;
import 'package:inventory_app/domain/models/stock_transaction.dart' as _i7;
import 'package:inventory_app/domain/repositories/i_product_repository.dart'
    as _i2;
import 'package:inventory_app/domain/usecases/adjust_stock_usecase.dart' as _i9;
import 'package:inventory_app/domain/usecases/create_product_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i2.IProductRepository {
  @override
  _i3.Future<List<_i4.Product>> getProducts({
    required _i5.ProductFilter? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#filter: filter}),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Product>>.value(
              <_i4.Product>[],
            ),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Future<void> saveProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#saveProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Product>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Product>>.value(
              <_i4.Product>[],
            ),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Future<void> addCategoryToProduct(int? productId, int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#addCategoryToProduct, [productId, categoryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeCategoryFromProduct(int? productId, int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCategoryFromProduct, [
              productId,
              categoryId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStock(
    int? productId,
    int? quantityDelta,
    _i6.StockAdjustmentReason? reason, {
    String? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateStock,
              [productId, quantityDelta, reason],
              {#user: user},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.StockTransaction>> getStockHistory(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getStockHistory, [productId]),
            returnValue: _i3.Future<List<_i7.StockTransaction>>.value(
              <_i7.StockTransaction>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i7.StockTransaction>>.value(
                  <_i7.StockTransaction>[],
                ),
          )
          as _i3.Future<List<_i7.StockTransaction>>);
}

/// A class which mocks [CreateProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateProductUseCase extends _i1.Mock
    implements _i8.CreateProductUseCase {
  @override
  _i3.Future<void> execute(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AdjustStockUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdjustStockUseCase extends _i1.Mock
    implements _i9.AdjustStockUseCase {
  @override
  _i3.Future<void> execute({
    required int? productId,
    required int? quantityDelta,
    required _i6.StockAdjustmentReason? reason,
    String? user = 'Local_user',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #productId: productId,
              #quantityDelta: quantityDelta,
              #reason: reason,
              #user: user,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
